var webpack = require('webpack');
module.exports = {
    entry:{
        main:"./src/js/main.js"
    },
    output:{
        path:__dirname,
        filename:'public/js/[name].build.js'
    },
    module:{
        loaders:[
            {
                test:/\.vue$/,
                loader:'vue'
            },
            {
                test:/\.js$/,
                loader:'babel',
                exclude:/node_modules/
            },
            {
                test:/\.css$/,
                loader:'style!css'
            }
        ]
    },
    vue:{
        loaders:{
            scss:"sass"
        }
    },
    babel:{
        presets:['es2015'],
        plugins:['transform-runtime']
    }
}